apiVersion: v2
name: pr-lens-git-backend
description: A lightweight PR Lens canvas server, with a git repository as the store
type: application
version: 0.5.0
appVersion: 0.5.0
kubeVersion: '>=1.25.0-0'
home: https://github.com/thejoeejoee/pr-lens-git-backend
sources:
  - https://github.com/thejoeejoee/pr-lens-git-backend
keywords:
  - pr-lens
  - canvas
  - diagram
  - git
maintainers:
  - name: thejoeejoee
