import type { GraphDoc } from "@coldtea/pr-lens-schema";

import type { Canvas } from "./canvas.ts";
import { draw, type Drawing } from "./render/draw.ts";

/**
 * Synthetic, logically representative sample architectures for the /demo route.
 *
 * Based on real GitHub PR #17 (thejoeejoee/pr-lens-git-backend/pull/17):
 * "feat(helm): let the ingress answer on more than one host".
 *
 * Provides two sample configurations:
 * (a) DEMO_SINGLE_DOC: exactly 1 diagram
 * (b) DEMO_MULTI_DOC: 6 diagrams demonstrating deep topology across multiple views
 */

export const DEMO_SINGLE_DOC: GraphDoc = {
  schemaVersion: "0.3.0",
  kind: "graph",
  id: "demo-single",
  title: "feat(helm): let the ingress answer on more than one host",
  summary:
    "Extend Helm chart ingress templates to bind multiple domain hosts with TLS SNI termination, routing traffic across public and internal gateway endpoints.",
  lenses: ["architecture"],
  provenance: {
    repo: {
      owner: "thejoeejoee",
      name: "pr-lens-git-backend",
      host: "github.com",
    },
    base: {
      sha: "14e5db8be9f2ec8d9c23e75d258c3493c3020cd3",
      ref: "main",
    },
    head: {
      sha: "25b6ff0598c0578d78bcdff624e768bdfd0d8dac",
      ref: "feat/ingress-hosts",
    },
    pullRequest: {
      number: 17,
      title: "feat(helm): let the ingress answer on more than one host",
      url: "https://github.com/thejoeejoee/pr-lens-git-backend/pull/17",
    },
    generator: {
      name: "pr-lens-demo",
      version: "0.6.0",
    },
  },
  lanes: [
    {
      id: "edge",
      label: "Edge & Ingress",
      order: 1,
      delta: "modified",
    },
    {
      id: "routing",
      label: "Host Rule Evaluation",
      order: 2,
      delta: "added",
    },
    {
      id: "backend",
      label: "Upstream Cluster Services",
      order: 3,
      delta: "unchanged",
    },
  ],
  nodes: [
    {
      id: "dns-clients",
      label: "DNS & External Clients",
      kind: "route",
      delta: "modified",
      lane: "edge",
      summary: "Directs requests across prlens.company.org and internal.prlens.net",
      files: [],
      badges: ["DNS", "SNI"],
    },
    {
      id: "traefik-ingress",
      label: "Traefik Ingress Controller",
      kind: "service",
      delta: "modified",
      lane: "edge",
      summary: "Terminates multi-SAN TLS and evaluates Host header routing rules",
      files: [{ path: "charts/pr-lens/templates/ingress.yaml" }, { path: "charts/pr-lens/values.yaml" }],
      badges: ["Ingress", "Helm"],
    },
    {
      id: "host-router",
      label: "Multi-Host Rule Matrix",
      kind: "service",
      delta: "added",
      lane: "routing",
      summary: "Dynamically maps .Values.ingress.hosts[*] to backend cluster services",
      files: [{ path: "charts/pr-lens/templates/ingress.yaml" }],
      badges: ["K8s", "SNI"],
    },
    {
      id: "prlens-backend",
      label: "PR Lens Backend Service",
      kind: "service",
      delta: "unchanged",
      lane: "backend",
      summary: "Core Node.js canvas rendering and git storage daemon",
      files: [],
      badges: ["Node.js", "Port 8787"],
    },
  ],
  edges: [
    {
      id: "e-dns-ingress",
      from: "dns-clients",
      to: "traefik-ingress",
      kind: "call",
      delta: "modified",
      label: "HTTPS 443 (multiple SNI)",
      emphasis: "hero",
      animated: true,
      files: [],
    },
    {
      id: "e-ingress-router",
      from: "traefik-ingress",
      to: "host-router",
      kind: "call",
      delta: "added",
      label: "eval Host header rules",
      emphasis: "normal",
      animated: true,
      files: [],
    },
    {
      id: "e-router-backend",
      from: "host-router",
      to: "prlens-backend",
      kind: "rpc",
      delta: "added",
      label: "forward /c/* and /api/*",
      emphasis: "hero",
      animated: true,
      files: [],
    },
  ],
  views: [
    {
      id: "ingress-topology",
      title: "Multi-Host Ingress Architecture",
      lens: "architecture",
      defaultOpen: true,
      scope: { kind: "all" },
      children: [],
    },
  ],
  flows: [],
};

export const DEMO_MULTI_DOC: GraphDoc = {
  schemaVersion: "0.3.0",
  kind: "graph",
  id: "demo-multi",
  title: "feat(helm): let the ingress answer on more than one host",
  summary:
    "Production multi-host topology: cert-manager SAN automation, high-availability rendering pods, stateful Git mirror persistence, and Prometheus observability.",
  lenses: ["architecture", "data-flow"],
  provenance: {
    repo: {
      owner: "thejoeejoee",
      name: "pr-lens-git-backend",
      host: "github.com",
    },
    base: {
      sha: "14e5db8be9f2ec8d9c23e75d258c3493c3020cd3",
      ref: "main",
    },
    head: {
      sha: "25b6ff0598c0578d78bcdff624e768bdfd0d8dac",
      ref: "feat/ingress-hosts",
    },
    pullRequest: {
      number: 17,
      title: "feat(helm): let the ingress answer on more than one host",
      url: "https://github.com/thejoeejoee/pr-lens-git-backend/pull/17",
    },
    generator: {
      name: "pr-lens-demo",
      version: "0.6.0",
    },
  },
  lanes: [
    {
      id: "lane-edge",
      label: "Edge Ingress & Gateway",
      order: 1,
      delta: "modified",
    },
    {
      id: "lane-compute",
      label: "Backend Service Mesh",
      order: 2,
      delta: "modified",
    },
    {
      id: "lane-cache",
      label: "Distributed Cache Tier",
      order: 3,
      delta: "added",
    },
    {
      id: "lane-storage",
      label: "Git Storage & Disk Volume",
      order: 4,
      delta: "unchanged",
    },
    {
      id: "lane-ops",
      label: "Telemetry & SRE Pipeline",
      order: 5,
      delta: "added",
    },
  ],
  nodes: [
    {
      id: "traefik-edge",
      label: "Traefik Ingress Router",
      kind: "service",
      delta: "modified",
      lane: "lane-edge",
      summary: "Multi-host edge router with SNI routing and ACME challenge resolution",
      files: [{ path: "charts/pr-lens/templates/ingress.yaml" }],
      badges: ["Traefik v3", "K8s Ingress"],
    },
    {
      id: "cert-manager",
      label: "Cert-Manager Operator",
      kind: "service",
      delta: "added",
      lane: "lane-edge",
      summary: "Automated TLS SAN certificate manager renewing multi-host secrets",
      files: [{ path: "charts/pr-lens/templates/certificates.yaml" }],
      badges: ["Let's Encrypt", "ACME"],
    },
    {
      id: "rate-limiter",
      label: "Envoy Rate Limiter",
      kind: "service",
      delta: "added",
      lane: "lane-edge",
      summary: "Distributed rate limiter protecting backend clusters against burst traffic",
      files: [{ path: "charts/pr-lens/templates/ratelimit.yaml" }],
      badges: ["Envoy", "TokenBucket"],
    },
    {
      id: "backend-pod-1",
      label: "PR Lens Primary Pod",
      kind: "service",
      delta: "modified",
      lane: "lane-compute",
      summary: "Primary canvas rendering service managing transactions and write locks",
      files: [{ path: "src/server.ts", startLine: 1, endLine: 120 }],
      badges: ["Node.js", "Leader"],
    },
    {
      id: "backend-pod-2",
      label: "PR Lens Replica Pod",
      kind: "service",
      delta: "added",
      lane: "lane-compute",
      summary: "Horizontal read replica scaling SVG hero and content-addressed tile delivery",
      files: [{ path: "src/render/draw.ts" }],
      badges: ["Node.js", "Follower"],
    },
    {
      id: "worker-pool",
      label: "Resvg Raster Worker",
      kind: "job",
      delta: "added",
      lane: "lane-compute",
      summary: "Background worker pool handling heavy rasterization and SVG compression",
      files: [{ path: "src/render/cache.ts" }],
      badges: ["WorkerPool", "Resvg"],
    },
    {
      id: "redis-cluster",
      label: "Redis LRU Cache",
      kind: "cache",
      delta: "added",
      lane: "lane-cache",
      summary: "Distributed in-memory LRU cache storing pre-rendered SVG assets and etags",
      files: [{ path: "src/render/cache.ts" }],
      badges: ["Redis 7", "Cluster"],
    },
    {
      id: "git-mirror",
      label: "Git Remote Mirror",
      kind: "datastore",
      delta: "unchanged",
      lane: "lane-storage",
      summary: "Authoritative Git repository mirror storing versioned canvas documents",
      files: [{ path: "src/store/git.ts" }],
      badges: ["Git Bare", "SSH"],
    },
    {
      id: "sharded-volume",
      label: "Sharded Git Volume",
      kind: "datastore",
      delta: "modified",
      lane: "lane-storage",
      summary: "High-IOPS persistent storage volume for Git objects and packfiles",
      files: [{ path: "charts/pr-lens/templates/pvc.yaml" }],
      badges: ["PVC 500Gi", "XFS"],
    },
    {
      id: "sqlite-wal",
      label: "SQLite Token WAL",
      kind: "datastore",
      delta: "added",
      lane: "lane-storage",
      summary: "Embedded ACID index tracking canvas IDs, token hashes, and commit SHAs",
      files: [{ path: "src/store/sqlite.ts" }],
      badges: ["SQLite", "WAL Index"],
    },
    {
      id: "prometheus",
      label: "Prometheus Collector",
      kind: "service",
      delta: "added",
      lane: "lane-ops",
      summary: "Time-series scraper gathering latency percentiles, rates, and health",
      files: [{ path: "charts/pr-lens/templates/service-monitor.yaml" }],
      badges: ["Prometheus", "v2.52"],
    },
    {
      id: "grafana-dashboard",
      label: "SRE Grafana Board",
      kind: "ui",
      delta: "added",
      lane: "lane-ops",
      summary: "Interactive operations dashboard monitoring p99 rendering latencies",
      files: [{ path: "charts/pr-lens/dashboards/overview.json" }],
      badges: ["Grafana", "SLO"],
    },
    {
      id: "alertmanager",
      label: "AlertManager Rules",
      kind: "config",
      delta: "added",
      lane: "lane-ops",
      summary: "Alerting routing rules triggering escalations on degraded replicas",
      files: [{ path: "charts/pr-lens/alerts/rules.yaml" }],
      badges: ["AlertManager", "PagerDuty"],
    },
  ],
  edges: [
    {
      id: "e-edge-cert",
      from: "traefik-edge",
      to: "cert-manager",
      kind: "call",
      delta: "added",
      label: "request SAN certs",
      emphasis: "normal",
      animated: true,
      files: [],
    },
    {
      id: "e-edge-limit",
      from: "traefik-edge",
      to: "rate-limiter",
      kind: "call",
      delta: "added",
      label: "check ratelimit",
      emphasis: "normal",
      animated: true,
      files: [],
    },
    {
      id: "e-edge-pod1",
      from: "traefik-edge",
      to: "backend-pod-1",
      kind: "call",
      delta: "modified",
      label: "forward /c/* and /api/*",
      emphasis: "hero",
      animated: true,
      files: [],
    },
    {
      id: "e-edge-pod2",
      from: "traefik-edge",
      to: "backend-pod-2",
      kind: "call",
      delta: "added",
      label: "load balance reads",
      emphasis: "normal",
      animated: true,
      files: [],
    },
    {
      id: "e-pod1-worker",
      from: "backend-pod-1",
      to: "worker-pool",
      kind: "queue",
      delta: "added",
      label: "dispatch render job",
      emphasis: "normal",
      animated: true,
      files: [],
    },
    {
      id: "e-pod1-cache",
      from: "backend-pod-1",
      to: "redis-cluster",
      kind: "call",
      delta: "added",
      label: "cache SVG & ETag",
      emphasis: "normal",
      animated: true,
      files: [],
    },
    {
      id: "e-pod2-cache",
      from: "backend-pod-2",
      to: "redis-cluster",
      kind: "call",
      delta: "added",
      label: "fetch cached tiles",
      emphasis: "normal",
      animated: true,
      files: [],
    },
    {
      id: "e-pod1-git",
      from: "backend-pod-1",
      to: "git-mirror",
      kind: "data",
      delta: "unchanged",
      label: "git push canvas.json",
      emphasis: "hero",
      animated: false,
      files: [],
    },
    {
      id: "e-pod1-vol",
      from: "backend-pod-1",
      to: "sharded-volume",
      kind: "data",
      delta: "modified",
      label: "commit packfile",
      emphasis: "normal",
      animated: false,
      files: [],
    },
    {
      id: "e-pod1-wal",
      from: "git-mirror",
      to: "sqlite-wal",
      kind: "data",
      delta: "added",
      label: "record rev token",
      emphasis: "normal",
      animated: true,
      files: [],
    },
    {
      id: "e-pod2-git",
      from: "backend-pod-2",
      to: "git-mirror",
      kind: "data",
      delta: "added",
      label: "git fetch & pull",
      emphasis: "normal",
      animated: true,
      files: [],
    },
    {
      id: "e-prom-scrape-1",
      from: "prometheus",
      to: "backend-pod-1",
      kind: "event",
      delta: "added",
      label: "scrape /healthz",
      emphasis: "normal",
      animated: true,
      files: [],
    },
    {
      id: "e-prom-scrape-2",
      from: "prometheus",
      to: "backend-pod-2",
      kind: "event",
      delta: "added",
      label: "scrape /metrics",
      emphasis: "normal",
      animated: true,
      files: [],
    },
    {
      id: "e-prom-alert",
      from: "prometheus",
      to: "alertmanager",
      kind: "event",
      delta: "added",
      label: "fire alert",
      emphasis: "normal",
      animated: true,
      files: [],
    },
    {
      id: "e-grafana-prom",
      from: "grafana-dashboard",
      to: "prometheus",
      kind: "call",
      delta: "added",
      label: "query PromQL",
      emphasis: "normal",
      animated: true,
      files: [],
    },
  ],
  views: [
    {
      id: "v-edge",
      title: "1. Multi-Host Edge Routing & TLS",
      lens: "architecture",
      defaultOpen: true,
      scope: {
        kind: "selection",
        lanes: ["lane-edge", "lane-compute"],
        nodes: ["traefik-edge", "cert-manager", "rate-limiter", "backend-pod-1"],
        edges: [],
        flows: [],
      },
      children: [],
    },
    {
      id: "v-tls",
      title: "2. TLS SNI Handshake & ACME Flow",
      lens: "data-flow",
      defaultOpen: false,
      scope: {
        kind: "selection",
        lanes: [],
        nodes: [],
        edges: [],
        flows: ["f-tls"],
      },
      children: [],
    },
    {
      id: "v-cluster",
      title: "3. Backend Service Mesh & Cache",
      lens: "architecture",
      defaultOpen: false,
      scope: {
        kind: "selection",
        lanes: ["lane-compute", "lane-cache"],
        nodes: ["traefik-edge", "backend-pod-1", "backend-pod-2", "worker-pool", "redis-cluster"],
        edges: [],
        flows: [],
      },
      children: [],
    },
    {
      id: "v-storage",
      title: "4. Git Mirror & Sharded Persistence",
      lens: "architecture",
      defaultOpen: false,
      scope: {
        kind: "selection",
        lanes: ["lane-storage"],
        nodes: ["backend-pod-1", "git-mirror", "sharded-volume", "sqlite-wal"],
        edges: [],
        flows: [],
      },
      children: [],
    },
    {
      id: "v-replication",
      title: "5. Canvas Push & Replica Sync Pipeline",
      lens: "data-flow",
      defaultOpen: false,
      scope: {
        kind: "selection",
        lanes: [],
        nodes: [],
        edges: [],
        flows: ["f-sync"],
      },
      children: [],
    },
    {
      id: "v-telemetry",
      title: "6. Prometheus Telemetry & Alerts",
      lens: "architecture",
      defaultOpen: false,
      scope: {
        kind: "selection",
        lanes: ["lane-ops", "lane-compute"],
        nodes: ["backend-pod-1", "backend-pod-2", "prometheus", "grafana-dashboard", "alertmanager"],
        edges: [],
        flows: [],
      },
      children: [],
    },
  ],
  flows: [
    {
      id: "f-tls",
      title: "TLS SNI Certificate Issuance",
      delta: "added",
      participants: [
        { node: "traefik-edge", label: "Ingress Router" },
        { node: "cert-manager", label: "Cert Manager" },
        { node: "backend-pod-1", label: "Backend Primary" },
      ],
      messages: [
        {
          id: "m1",
          from: "traefik-edge",
          to: "cert-manager",
          label: "1. Challenge multi-host SAN",
          kind: "sync",
          delta: "added",
          animated: true,
          files: [],
        },
        {
          id: "m2",
          from: "cert-manager",
          to: "traefik-edge",
          label: "2. Deploy TLS secret",
          kind: "return",
          delta: "added",
          animated: true,
          files: [],
        },
        {
          id: "m3",
          from: "traefik-edge",
          to: "backend-pod-1",
          label: "3. Dispatch validated HTTPS request",
          kind: "sync",
          delta: "modified",
          animated: true,
          files: [],
        },
      ],
    },
    {
      id: "f-sync",
      title: "Canvas Write & Replica Sync",
      delta: "added",
      participants: [
        { node: "backend-pod-1", label: "Primary Pod" },
        { node: "git-mirror", label: "Git Mirror" },
        { node: "backend-pod-2", label: "Replica Pod" },
      ],
      messages: [
        {
          id: "ms1",
          from: "backend-pod-1",
          to: "git-mirror",
          label: "1. Commit & push canvas blob",
          kind: "sync",
          delta: "added",
          animated: true,
          files: [],
        },
        {
          id: "ms2",
          from: "git-mirror",
          to: "backend-pod-2",
          label: "2. Mirror sync event",
          kind: "async",
          delta: "added",
          animated: true,
          files: [],
        },
      ],
    },
  ],
};

/** Pre-rendered drawing bundles for instant zero-overhead serving on /demo. */
export type DemoFixture = {
  id: string;
  doc: GraphDoc;
  drawing: Drawing;
  canvas: Canvas;
};

const makeDemo = (id: string, doc: GraphDoc): DemoFixture => {
  const drawing = draw(doc);
  const canvas: Canvas = {
    id,
    rev: 1,
    document: doc,
    drawing,
  };
  return { id, doc, drawing, canvas };
};

let cachedSingle: DemoFixture | undefined;
let cachedMulti: DemoFixture | undefined;

export const getDemoFixture = (name?: string): DemoFixture => {
  if (name === "single" || name === "1" || name === "billing") {
    return (cachedSingle ??= makeDemo("demo-single", DEMO_SINGLE_DOC));
  }
  return (cachedMulti ??= makeDemo("demo-multi", DEMO_MULTI_DOC));
};

export const getDemoImage = (fileName: string): string | undefined => {
  const multi = getDemoFixture("multi");
  const single = getDemoFixture("single");
  return multi.drawing.images.get(fileName) ?? single.drawing.images.get(fileName);
};
